In [2]:
import warnings

import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

warnings.filterwarnings(action='ignore', category=UserWarning)
warnings.filterwarnings(action='ignore', category=RuntimeWarning)

df = pd.read_table('./final2.tsv')  # the same as the Supplementary Table 1.
df['reference wesTMB'] = df['sample'].map({'A1': 103.0021, 'B1': 148.34,
                                           'C1': 112.2377, 'D1': 4.97, 'E1': .0})

In [3]:
tp2_model = ols('wesTMB ~ C(panel_id) * C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp2_ancova_table = sm.stats.anova_lm(tp2_model, typ=2)
print('type2: panel_id * product + sample + rTMB')
print(tp2_ancova_table)

tp3_model = ols('wesTMB ~ C(panel_id) * C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp3_ancova_table = sm.stats.anova_lm(tp3_model, typ=3)
print('type3: panel_id * product + sample + rTMB')
print(tp3_ancova_table)

tp2_model2 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp2_ancova_table2 = sm.stats.anova_lm(tp2_model2, typ=2)
print('type2: panel_id + product + sample + rTMB')
print(tp2_ancova_table2)

tp3_model2 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp3_ancova_table2 = sm.stats.anova_lm(tp3_model2, typ=3)
print('type3: panel_id + product + sample + rTMB')
print(tp3_ancova_table2)

type2: panel_id * product + sample + rTMB
                               sum_sq      df         F    PR(>F)
C(panel_id)                       NaN    54.0       NaN       NaN
C(product)                        NaN    40.0       NaN       NaN
C(sample)                   37.444812     4.0  0.011506  0.914678
C(panel_id):C(product)   20220.198254  2160.0  0.011506  0.914678
Q("reference wesTMB")        9.361203     1.0  0.011506  0.914678
Residual                176553.830064   217.0       NaN       NaN
type3: panel_id * product + sample + rTMB
                               sum_sq      df         F    PR(>F)
Intercept                    9.361203     1.0  0.011506  0.914678
C(panel_id)                504.542159    54.0  0.011484  0.914759
C(product)                 368.985994    40.0  0.011338  0.915300
C(sample)                   37.444812     4.0  0.011506  0.914678
C(panel_id):C(product)   20220.198254  2160.0  0.011506  0.914678
Q("reference wesTMB")        9.361203     1.0  0.011506  0.914678
Residual                176553.830064   217.0       NaN       NaN
type2: panel_id + product + sample + rTMB
                              sum_sq     df           F        PR(>F)
C(panel_id)            173678.031394   54.0    3.953245  3.460961e-13
C(product)             172048.913324   40.0    5.286821  3.207551e-16
C(sample)                7796.875955    4.0    2.395870  6.916494e-02
Q("reference wesTMB")  258204.704006    1.0  317.370669  2.398611e-44
Residual               176545.680515  217.0         NaN           NaN
type3: panel_id + product + sample + rTMB
                              sum_sq     df           F        PR(>F)
Intercept                1630.033505    1.0    2.003545  1.583653e-01
C(panel_id)            173678.031394   54.0    3.953245  3.460961e-13
C(product)             172048.913324   40.0    5.286821  3.207551e-16
C(sample)                7796.875955    4.0    2.395870  6.916494e-02
Q("reference wesTMB")  258204.704006    1.0  317.370669  2.398611e-44
Residual               176545.680515  217.0         NaN           NaN

In [4]:
tp2_model = ols('wesTMB ~ C(panel_id) * C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp2_ancova_table = sm.stats.anova_lm(tp2_model, typ=2)
tp2_ancova_table['eta_sq'] = tp2_ancova_table['sum_sq'] / tp2_ancova_table['sum_sq'].sum()
print('type2: panel_id * product + sample + rTMB')
print(tp2_ancova_table)

tp3_model = ols('wesTMB ~ C(panel_id) * C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp3_ancova_table = sm.stats.anova_lm(tp3_model, typ=3)
tp3_ancova_table['eta_sq'] = tp2_ancova_table['sum_sq'] / tp3_ancova_table['sum_sq'].sum()
print('type3: panel_id * product + sample + rTMB')
print(tp3_ancova_table)

tp2_model2 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp2_ancova_table2 = sm.stats.anova_lm(tp2_model2, typ=2)
tp2_ancova_table2['eta_sq'] = tp2_ancova_table2['sum_sq'] / tp2_ancova_table2['sum_sq'].sum()
print('type2: panel_id + product + sample + rTMB')
print(tp2_ancova_table2)

tp3_model2 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp3_ancova_table2 = sm.stats.anova_lm(tp3_model2, typ=3)
tp3_ancova_table2['eta_sq'] = tp3_ancova_table2['sum_sq'] / tp3_ancova_table2['sum_sq'].sum()
print('type3: panel_id + product + sample + rTMB')
print(tp3_ancova_table2)

type2: panel_id * product + sample + rTMB
                               sum_sq      df         F    PR(>F)    eta_sq
C(panel_id)                       NaN    54.0       NaN       NaN       NaN
C(product)                        NaN    40.0       NaN       NaN       NaN
C(sample)                   37.444812     4.0  0.011506  0.914678  0.000190
C(panel_id):C(product)   20220.198254  2160.0  0.011506  0.914678  0.102734
Q("reference wesTMB")        9.361203     1.0  0.011506  0.914678  0.000048
Residual                176553.830064   217.0       NaN       NaN  0.897028
type3: panel_id * product + sample + rTMB
                               sum_sq      df         F    PR(>F)    eta_sq
Intercept                    9.361203     1.0  0.011506  0.914678       NaN
C(panel_id)                504.542159    54.0  0.011484  0.914759       NaN
C(product)                 368.985994    40.0  0.011338  0.915300       NaN
C(sample)                   37.444812     4.0  0.011506  0.914678  0.000189
C(panel_id):C(product)   20220.198254  2160.0  0.011506  0.914678  0.102275
Q("reference wesTMB")        9.361203     1.0  0.011506  0.914678  0.000047
Residual                176553.830064   217.0       NaN       NaN  0.893022
type2: panel_id + product + sample + rTMB
                              sum_sq     df           F        PR(>F)  \
C(panel_id)            173678.031394   54.0    3.953245  3.460961e-13
C(product)             172048.913324   40.0    5.286821  3.207551e-16
C(sample)                7796.875955    4.0    2.395870  6.916494e-02
Q("reference wesTMB")  258204.704006    1.0  317.370669  2.398611e-44
Residual               176545.680515  217.0         NaN           NaN

                         eta_sq
C(panel_id)            0.220327
C(product)             0.218260
C(sample)              0.009891
Q("reference wesTMB")  0.327557
Residual               0.223965
type3: panel_id + product + sample + rTMB
                              sum_sq     df           F        PR(>F)  \
Intercept                1630.033505    1.0    2.003545  1.583653e-01
C(panel_id)            173678.031394   54.0    3.953245  3.460961e-13
C(product)             172048.913324   40.0    5.286821  3.207551e-16
C(sample)                7796.875955    4.0    2.395870  6.916494e-02
Q("reference wesTMB")  258204.704006    1.0  317.370669  2.398611e-44
Residual               176545.680515  217.0         NaN           NaN

                         eta_sq
Intercept              0.002064
C(panel_id)            0.219872
C(product)             0.217810
C(sample)              0.009871
Q("reference wesTMB")  0.326881
Residual               0.223503

In [5]:
tp2_model3 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) * Q("reference wesTMB")', data=df).fit()
tp2_ancova_table3 = sm.stats.anova_lm(tp2_model3, typ=2)
tp2_ancova_table3['eta_sq'] = tp2_ancova_table3['sum_sq'] / tp2_ancova_table3['sum_sq'].sum()
print('type2: panel_id + product + sample * rTMB')
print(tp2_ancova_table3)

tp3_model3 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) * Q("reference wesTMB")', data=df).fit()
tp3_ancova_table3 = sm.stats.anova_lm(tp3_model3, typ=3)
tp3_ancova_table3['eta_sq'] = tp3_ancova_table3['sum_sq'] / tp3_ancova_table3['sum_sq'].sum()
print('type3: panel_id + product + sample * rTMB')
print(tp3_ancova_table3)

tp2_model4 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp2_ancova_table4 = sm.stats.anova_lm(tp2_model4, typ=2)
tp2_ancova_table4['eta_sq'] = tp2_ancova_table4['sum_sq'] / tp2_ancova_table4['sum_sq'].sum()
print('type2: panel_id + product + sample + rTMB')
print(tp2_ancova_table4)

tp3_model4 = ols('wesTMB ~ C(panel_id) + C(product) + C(sample) + Q("reference wesTMB")', data=df).fit()
tp3_ancova_table4 = sm.stats.anova_lm(tp3_model4, typ=3)
tp3_ancova_table4['eta_sq'] = tp3_ancova_table4['sum_sq'] / tp3_ancova_table4['sum_sq'].sum()
print('type3: panel_id + product + sample + rTMB')
print(tp3_ancova_table4)

type2: panel_id + product + sample * rTMB
                                        sum_sq     df         F        PR(>F)  \
C(panel_id)                      173678.031394   54.0  3.953245  3.460961e-13
C(product)                       172048.913324   40.0  5.286821  3.207551e-16
C(sample)                             0.010393    4.0  0.000003  1.000000e+00
Q("reference wesTMB")                      NaN    1.0       NaN           NaN
C(sample):Q("reference wesTMB")    7796.875955    4.0  2.395870  6.916494e-02
Residual                         176545.680515  217.0       NaN           NaN

                                       eta_sq
C(panel_id)                      3.276514e-01
C(product)                       3.245780e-01
C(sample)                        1.960639e-08
Q("reference wesTMB")                     NaN
C(sample):Q("reference wesTMB")  1.470916e-02
Residual                         3.330614e-01
type3: panel_id + product + sample * rTMB
                                        sum_sq     df          F  \
Intercept                           579.918547    1.0   0.712803
C(panel_id)                      173678.031394   54.0   3.953245
C(product)                       172048.913324   40.0   5.286821
C(sample)                          7796.875954    4.0   2.395870
Q("reference wesTMB")             59979.793268    1.0  73.723781
C(sample):Q("reference wesTMB")    7796.875955    4.0   2.395870
Residual                         176545.680515  217.0        NaN

                                       PR(>F)    eta_sq
Intercept                        3.994446e-01  0.000969
C(panel_id)                      3.460961e-13  0.290225
C(product)                       3.207551e-16  0.287502
C(sample)                        6.916494e-02  0.013029
Q("reference wesTMB")            1.752800e-15  0.100229
C(sample):Q("reference wesTMB")  6.916494e-02  0.013029
Residual                                  NaN  0.295017
type2: panel_id + product + sample + rTMB
                              sum_sq     df           F        PR(>F)  \
C(panel_id)            173678.031394   54.0    3.953245  3.460961e-13
C(product)             172048.913324   40.0    5.286821  3.207551e-16
C(sample)                7796.875955    4.0    2.395870  6.916494e-02
Q("reference wesTMB")  258204.704006    1.0  317.370669  2.398611e-44
Residual               176545.680515  217.0         NaN           NaN

                         eta_sq
C(panel_id)            0.220327
C(product)             0.218260
C(sample)              0.009891
Q("reference wesTMB")  0.327557
Residual               0.223965
type3: panel_id + product + sample + rTMB
                              sum_sq     df           F        PR(>F)  \
Intercept                1630.033505    1.0    2.003545  1.583653e-01
C(panel_id)            173678.031394   54.0    3.953245  3.460961e-13
C(product)             172048.913324   40.0    5.286821  3.207551e-16
C(sample)                7796.875955    4.0    2.395870  6.916494e-02
Q("reference wesTMB")  258204.704006    1.0  317.370669  2.398611e-44
Residual               176545.680515  217.0         NaN           NaN

                         eta_sq
Intercept              0.002064
C(panel_id)            0.219872
C(product)             0.217810
C(sample)              0.009871
Q("reference wesTMB")  0.326881
Residual               0.223503

In [6]:
only_abcde = df.query('group != "other"').copy(deep=True)
only_abcde_tp2_model = ols('wesTMB ~ C(panel_id) * C(product) + Q("reference wesTMB")', data=only_abcde).fit()
only_abcde_tp2_ancova_table = sm.stats.anova_lm(only_abcde_tp2_model, typ=2)
only_abcde_tp2_ancova_table['eta_sq'] = only_abcde_tp2_ancova_table['sum_sq'] / only_abcde_tp2_ancova_table['sum_sq'].sum()
print('type2: panel_id * product + sample + rTMB')
print(only_abcde_tp2_ancova_table)

only_abcde_tp3_model = ols('wesTMB ~ C(panel_id) * C(product) + Q("reference wesTMB")', data=only_abcde).fit()
only_abcde_tp3_ancova_table = sm.stats.anova_lm(only_abcde_tp3_model, typ=3)
only_abcde_tp3_ancova_table['eta_sq'] = only_abcde_tp3_ancova_table['sum_sq'] / only_abcde_tp3_ancova_table['sum_sq'].sum()
print('type3: panel_id * product + sample + rTMB')
print(only_abcde_tp3_ancova_table)

only_abcde_tp2_model2 = ols('wesTMB ~ C(panel_id) + C(product) + Q("reference wesTMB")', data=only_abcde).fit()
only_abcde_tp2_ancova_table2 = sm.stats.anova_lm(only_abcde_tp2_model2, typ=2)
only_abcde_tp2_ancova_table2['eta_sq'] = only_abcde_tp2_ancova_table2['sum_sq'] / only_abcde_tp2_ancova_table2['sum_sq'].sum()
print('type2: panel_id + product + sample + rTMB')
print(only_abcde_tp2_ancova_table2)

only_abcde_tp3_model2 = ols('wesTMB ~ C(panel_id) + C(product) + Q("reference wesTMB")', data=only_abcde).fit()
only_abcde_tp3_ancova_table2 = sm.stats.anova_lm(only_abcde_tp3_model2, typ=3)
only_abcde_tp3_ancova_table2['eta_sq'] = only_abcde_tp3_ancova_table2['sum_sq'] / only_abcde_tp3_ancova_table2['sum_sq'].sum()
print('type3: panel_id + product + sample + rTMB')
print(only_abcde_tp3_ancova_table2)

type2: panel_id * product + sample + rTMB
                               sum_sq     df           F        PR(>F)  \
C(panel_id)             520046.632091   20.0   28.218923  4.466251e-10
C(product)              156013.989627    6.0   28.218923  4.466251e-10
C(panel_id):C(product)  487433.518030  120.0    4.408210  2.339075e-06
Q("reference wesTMB")   712911.874831    1.0  773.684678  7.804487e-44
Residual                 76480.363771   83.0         NaN           NaN

                          eta_sq
C(panel_id)             0.266296
C(product)              0.079889
C(panel_id):C(product)  0.249596
Q("reference wesTMB")   0.365055
Residual                0.039163
type3: panel_id * product + sample + rTMB
                               sum_sq     df           F        PR(>F)  \
Intercept                   32.082310    1.0    0.034817  8.524346e-01
C(panel_id)              69136.092398   20.0    3.751483  1.083755e-05
C(product)               67434.541844    6.0   12.197176  8.639513e-10
C(panel_id):C(product)  487433.518030  120.0    4.408210  2.339075e-06
Q("reference wesTMB")   712911.874831    1.0  773.684678  7.804487e-44
Residual                 76480.363771   83.0         NaN           NaN

                          eta_sq
Intercept               0.000023
C(panel_id)             0.048914
C(product)              0.047710
C(panel_id):C(product)  0.344859
Q("reference wesTMB")   0.504385
Residual                0.054110
type2: panel_id + product + sample + rTMB
                              sum_sq    df           F        PR(>F)    eta_sq
C(panel_id)             69136.092398  20.0    3.751483  1.083755e-05  0.074664
C(product)              67434.541844   6.0   12.197176  8.639513e-10  0.072826
Q("reference wesTMB")  712911.874831   1.0  773.684678  7.804487e-44  0.769914
Residual                76480.363771  83.0         NaN           NaN  0.082595
type3: panel_id + product + sample + rTMB
                              sum_sq    df           F        PR(>F)    eta_sq
Intercept                  32.082310   1.0    0.034817  8.524346e-01  0.000035
C(panel_id)             69136.092398  20.0    3.751483  1.083755e-05  0.074661
C(product)              67434.541844   6.0   12.197176  8.639513e-10  0.072824
Q("reference wesTMB")  712911.874831   1.0  773.684678  7.804487e-44  0.769887
Residual                76480.363771  83.0         NaN           NaN  0.082593

In [7]:
group_tp2_model = ols('wesTMB ~ C(panel_id) * C(group) + Q("reference wesTMB")', data=df).fit()
group_tp2_ancova_table = sm.stats.anova_lm(group_tp2_model, typ=2)
group_tp2_ancova_table['eta_sq'] = group_tp2_ancova_table['sum_sq'] / group_tp2_ancova_table['sum_sq'].sum()
print('type2: panel_id * product + sample + rTMB')
print(group_tp2_ancova_table[['df', 'F', 'PR(>F)', 'eta_sq']])

group_tp3_model = ols('wesTMB ~ C(panel_id) * C(group) + Q("reference wesTMB")', data=df).fit()
group_tp3_ancova_table = sm.stats.anova_lm(group_tp3_model, typ=3)
group_tp3_ancova_table['eta_sq'] = group_tp3_ancova_table['sum_sq'] / group_tp3_ancova_table['sum_sq'].sum()
print('type3: panel_id * product + sample + rTMB')
print(group_tp3_ancova_table[['df', 'F', 'PR(>F)', 'eta_sq']])

group_tp2_model2 = ols('wesTMB ~ C(panel_id) + C(group) + Q("reference wesTMB")', data=df).fit()
group_tp2_ancova_table2 = sm.stats.anova_lm(group_tp2_model2, typ=2)
group_tp2_ancova_table2['eta_sq'] = group_tp2_ancova_table2['sum_sq'] / group_tp2_ancova_table2['sum_sq'].sum()
print('type2: panel_id + product + sample + rTMB')
print(only_abcde_tp2_ancova_table2[['df', 'F', 'PR(>F)', 'eta_sq']])

group_tp3_model2 = ols('wesTMB ~ C(panel_id) + C(group) + Q("reference wesTMB")', data=df).fit()
group_tp3_ancova_table2 = sm.stats.anova_lm(group_tp3_model2, typ=3)
group_tp3_ancova_table2['eta_sq'] = group_tp3_ancova_table2['sum_sq'] / group_tp3_ancova_table2['sum_sq'].sum()
print('type3: panel_id + product + sample + rTMB')
print(only_abcde_tp3_ancova_table2[['df', 'F', 'PR(>F)', 'eta_sq']])

type2: panel_id * product + sample + rTMB
                          df            F         PR(>F)    eta_sq
C(panel_id)             54.0    39.827138   1.768699e-15  0.359880
C(group)                 7.0    31.301637   1.104847e-12  0.036665
C(panel_id):C(group)   378.0     4.116066   3.862608e-08  0.260351
Q("reference wesTMB")    1.0  1831.416329  2.440287e-108  0.306459
Residual               219.0          NaN            NaN  0.036646
type3: panel_id * product + sample + rTMB
                          df            F         PR(>F)    eta_sq
Intercept                1.0     0.985931   3.218347e-01  0.000253
C(panel_id)             54.0     3.879187   6.815061e-13  0.053695
C(group)                 7.0    12.067497   5.221708e-13  0.021653
C(panel_id):C(group)   378.0     4.116066   3.862608e-08  0.398817
Q("reference wesTMB")    1.0  1831.416329  2.440287e-108  0.469447
Residual               219.0          NaN            NaN  0.056136
type2: panel_id + product + sample + rTMB
                         df           F        PR(>F)    eta_sq
C(panel_id)            20.0    3.751483  1.083755e-05  0.074664
C(product)              6.0   12.197176  8.639513e-10  0.072826
Q("reference wesTMB")   1.0  773.684678  7.804487e-44  0.769914
Residual               83.0         NaN           NaN  0.082595
type3: panel_id + product + sample + rTMB
                         df           F        PR(>F)    eta_sq
Intercept               1.0    0.034817  8.524346e-01  0.000035
C(panel_id)            20.0    3.751483  1.083755e-05  0.074661
C(product)              6.0   12.197176  8.639513e-10  0.072824
Q("reference wesTMB")   1.0  773.684678  7.804487e-44  0.769887
Residual               83.0         NaN           NaN  0.082593

In [23]:
group_tp3_ancova_table[['df', 'F', 'PR(>F)', 'eta_sq']].copy(deep=True).reset_index(drop=False)

                   index     df            F         PR(>F)    eta_sq
0              Intercept    1.0     0.985931   3.218347e-01  0.000253
1            C(panel_id)   54.0     3.879187   6.815061e-13  0.053695
2               C(group)    7.0    12.067497   5.221708e-13  0.021653
3   C(panel_id):C(group)  378.0     4.116066   3.862608e-08  0.398817
4  Q("reference wesTMB")    1.0  1831.416329  2.440287e-108  0.469447
5               Residual  219.0          NaN            NaN  0.056136

In [24]:
group_tp3_ancova_table[['F', 'PR(>F)', 'eta_sq']].copy(deep=True).reset_index(drop=False).rename(columns={'index': 'factor'})

                  factor            F         PR(>F)    eta_sq
0              Intercept     0.985931   3.218347e-01  0.000253
1            C(panel_id)     3.879187   6.815061e-13  0.053695
2               C(group)    12.067497   5.221708e-13  0.021653
3   C(panel_id):C(group)     4.116066   3.862608e-08  0.398817
4  Q("reference wesTMB")  1831.416329  2.440287e-108  0.469447
5               Residual          NaN            NaN  0.056136

In [30]:
print(only_abcde_tp3_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 wesTMB   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.888
Method:                 Least Squares   F-statistic:                     40.41
Date:                Sun, 19 Nov 2023   Prob (F-statistic):           6.96e-35
Time:                        10:16:09   Log-Likelihood:                -495.01
No. Observations:                 105   AIC:                             1034.
Df Residuals:                      83   BIC:                             1092.
Df Model:                          21
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 2.6282     14.085      0.187      0.852     -25.387      30.643
C(panel_id)[T.p07b]                    8.153e-13     19.198   4.25e-14      1.000     -38.185      38.185
C(panel_id)[T.p07c]                      -1.7803     19.198     -0.093      0.926     -39.965      36.405
C(panel_id)[T.p07d]                      -0.5342     19.198     -0.028      0.978     -38.719      37.651
C(panel_id)[T.p10a]                      -2.2655      6.432     -0.352      0.726     -15.059      10.528
C(panel_id)[T.p10b]                      -1.4088      6.432     -0.219      0.827     -14.202      11.384
C(panel_id)[T.p10c]                      -1.9447      6.432     -0.302      0.763     -14.738      10.848
C(panel_id)[T.p10d]                      -1.5202      6.432     -0.236      0.814     -14.313      11.273
C(panel_id)[T.p10e]                      -1.4088      6.432     -0.219      0.827     -14.202      11.384
C(panel_id)[T.p23a]                      -8.7784      6.367     -1.379      0.172     -21.443       3.886
C(panel_id)[T.p23b]                       1.8221      6.367      0.286      0.775     -10.842      14.487
C(panel_id)[T.p23c]                      -0.7194      6.367     -0.113      0.910     -13.384      11.945
C(panel_id)[T.p30a]                       2.4893      6.367      0.391      0.697     -10.175      15.154
C(panel_id)[T.p30b]                       1.9459      6.367      0.306      0.761     -10.719      14.610
C(panel_id)[T.p30c]                       2.1001      6.367      0.330      0.742     -10.564      14.765
C(panel_id)[T.p33a]                      -9.8858      6.349     -1.557      0.123     -22.514       2.743
C(panel_id)[T.p33b]                      -6.5248      6.349     -1.028      0.307     -19.153       6.104
C(panel_id)[T.p36a]                      -4.3858      6.349     -0.691      0.492     -17.014       8.243
C(panel_id)[T.p36b]                      -9.5397      6.349     -1.502      0.137     -22.168       3.089
C(panel_id)[T.p40a]                      16.2022      6.349      2.552      0.013       3.574      28.831
C(panel_id)[T.p40b]                      16.2022      6.349      2.552      0.013       3.574      28.831
C(product)[T.p10]                        -8.5479     10.622     -0.805      0.423     -29.675      12.579
C(product)[T.p23]                        -7.6756      9.405     -0.816      0.417     -26.382      11.031
C(product)[T.p30]                         6.5353      9.405      0.695      0.489     -12.171      25.242
C(product)[T.p33]                       -16.4107      8.313     -1.974      0.052     -32.945       0.124
C(product)[T.p36]                       -13.9255      8.313     -1.675      0.098     -30.460       2.609
C(product)[T.p40]                        32.4043      8.313      3.898      0.000      15.870      48.939
C(panel_id)[T.p07b]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p07c]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p07d]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p10a]:C(product)[T.p10]    -2.2655      6.432     -0.352      0.726     -15.059      10.528
C(panel_id)[T.p10b]:C(product)[T.p10]    -1.4088      6.432     -0.219      0.827     -14.202      11.384
C(panel_id)[T.p10c]:C(product)[T.p10]    -1.9447      6.432     -0.302      0.763     -14.738      10.848
C(panel_id)[T.p10d]:C(product)[T.p10]    -1.5202      6.432     -0.236      0.814     -14.313      11.273
C(panel_id)[T.p10e]:C(product)[T.p10]    -1.4088      6.432     -0.219      0.827     -14.202      11.384
C(panel_id)[T.p23a]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p23b]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p23c]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p30a]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p30b]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p30c]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p33a]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p33b]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p36a]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p36b]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p40a]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p40b]:C(product)[T.p10]          0          0        nan        nan           0           0
C(panel_id)[T.p07b]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p07c]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p07d]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p10a]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p10b]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p10c]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p10d]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p10e]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p23a]:C(product)[T.p23]    -8.7784      6.367     -1.379      0.172     -21.443       3.886
C(panel_id)[T.p23b]:C(product)[T.p23]     1.8221      6.367      0.286      0.775     -10.842      14.487
C(panel_id)[T.p23c]:C(product)[T.p23]    -0.7194      6.367     -0.113      0.910     -13.384      11.945
C(panel_id)[T.p30a]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p30b]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p30c]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p33a]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p33b]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p36a]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p36b]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p40a]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p40b]:C(product)[T.p23]          0          0        nan        nan           0           0
C(panel_id)[T.p07b]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p07c]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p07d]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p10a]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p10b]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p10c]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p10d]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p10e]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p23a]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p23b]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p23c]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p30a]:C(product)[T.p30]     2.4893      6.367      0.391      0.697     -10.175      15.154
C(panel_id)[T.p30b]:C(product)[T.p30]     1.9459      6.367      0.306      0.761     -10.719      14.610
C(panel_id)[T.p30c]:C(product)[T.p30]     2.1001      6.367      0.330      0.742     -10.564      14.765
C(panel_id)[T.p33a]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p33b]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p36a]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p36b]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p40a]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p40b]:C(product)[T.p30]          0          0        nan        nan           0           0
C(panel_id)[T.p07b]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p07c]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p07d]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p10a]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p10b]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p10c]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p10d]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p10e]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p23a]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p23b]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p23c]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p30a]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p30b]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p30c]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p33a]:C(product)[T.p33]    -9.8858      6.349     -1.557      0.123     -22.514       2.743
C(panel_id)[T.p33b]:C(product)[T.p33]    -6.5248      6.349     -1.028      0.307     -19.153       6.104
C(panel_id)[T.p36a]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p36b]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p40a]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p40b]:C(product)[T.p33]          0          0        nan        nan           0           0
C(panel_id)[T.p07b]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p07c]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p07d]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p10a]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p10b]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p10c]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p10d]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p10e]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p23a]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p23b]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p23c]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p30a]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p30b]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p30c]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p33a]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p33b]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p36a]:C(product)[T.p36]    -4.3858      6.349     -0.691      0.492     -17.014       8.243
C(panel_id)[T.p36b]:C(product)[T.p36]    -9.5397      6.349     -1.502      0.137     -22.168       3.089
C(panel_id)[T.p40a]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p40b]:C(product)[T.p36]          0          0        nan        nan           0           0
C(panel_id)[T.p07b]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p07c]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p07d]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p10a]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p10b]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p10c]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p10d]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p10e]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p23a]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p23b]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p23c]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p30a]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p30b]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p30c]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p33a]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p33b]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p36a]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p36b]:C(product)[T.p40]          0          0        nan        nan           0           0
C(panel_id)[T.p40a]:C(product)[T.p40]    16.2022      6.349      2.552      0.013       3.574      28.831
C(panel_id)[T.p40b]:C(product)[T.p40]    16.2022      6.349      2.552      0.013       3.574      28.831
Q("reference wesTMB")                     1.3985      0.050     27.815      0.000       1.299       1.499
==============================================================================
Omnibus:                       45.678   Durbin-Watson:                   1.674
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              255.512
Skew:                           1.249   Prob(JB):                     3.28e-56
Kurtosis:                      10.222   Cond. No.                     1.03e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
[3] The smallest eigenvalue is 9.03e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [33]:
(only_abcde_tp3_ancova_table
 [['F', 'PR(>F)', 'eta_sq']]
 .copy(deep=True)
 .reset_index(drop=False)
 .rename(columns={'index': 'factor'})
 .to_csv('D:/RProject/tmb_article/grouped_westmb_value/only_abcde_anova.tsv',
         sep='\t', lineterminator='\n', encoding='utf-8', index=False))

(group_tp3_ancova_table
 [['F', 'PR(>F)', 'eta_sq']]
 .copy(deep=True)
 .reset_index(drop=False)
 .rename(columns={'index': 'factor'})
 .to_csv('D:/RProject/tmb_article/grouped_westmb_value/group_anova.tsv',
         sep='\t', lineterminator='\n', encoding='utf-8', index=False))